import { Tool } from "./types";

export const TOOLS_CATALOG: Tool[] = [
  // ========== NEW EXPERIMENTAL =========
  { name: "ModelScope", category: "AI & Image Editing", subcategory: "AI Content Generation", isRealDemo: true },
  { name: "Audio & Voice Synth Lab", category: "AI & Image Editing", subcategory: "Simulated Content/Text", isRealDemo: true },
  { name: "Interactive SQL Builder Sandbox", category: "Development & Code", subcategory: "Database & Backend", isRealDemo: true },
  { name: "CSS Keyframe Studio", category: "Development & Code", subcategory: "UI & Animations", isRealDemo: true },
  { name: "3D Physics Sandbox", category: "Development & Code", subcategory: "Canvas & Rendering", isRealDemo: true },
  { name: "a11y Contrast Checker", category: "Development & Code", subcategory: "Accessibility & Guidelines", isRealDemo: true },
  { name: "Color Palette Alchemist", category: "Development & Code", subcategory: "Tailwind UI Designer", isRealDemo: true },

  // ========== AI & IMAGE EDITING =========
  { name: "AI Writer", category: "AI & Image Editing", subcategory: "AI Content Generation", isRealDemo: true },
  { name: "AI Article Generator", category: "AI & Image Editing", subcategory: "AI Content Generation", isRealDemo: true },
  { name: "AI Poem Generator", category: "AI & Image Editing", subcategory: "AI Content Generation", isRealDemo: true },
  { name: "Acrostic Poem Generator", category: "AI & Image Editing", subcategory: "AI Content Generation", isRealDemo: true },
  { name: "AI Emoji Maker", category: "AI & Image Editing", subcategory: "AI Content Generation", isRealDemo: true },
  { name: "AI Clipart Generator", category: "AI & Image Editing", subcategory: "AI Content Generation", isRealDemo: true },
  
  { name: "AI Image Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters", isRealDemo: true },
  { name: "Free Nanobanana Image Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters", isRealDemo: true },
  { name: "Ollama Local Image Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters", isRealDemo: true },
  { name: "Hugging Face Space Loader", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters", isRealDemo: true },
  { name: "Free Turbo Image Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "Free Seedream Image Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "Free Flux Image Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "AI Photo To Anime", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "AI Photo To Cartoon", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "AI Manga Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "AI Doll Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "AI Caricature Maker", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "AI Action Figure Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "AI Photo To Pixel Art", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "Pixar AI Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "AI Lego Filter", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "Simpsons Character Generator", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "Retro PS2-Style", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "AI Kawaii Chibi Art", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },
  { name: "Ghibli Style", category: "AI & Image Editing", subcategory: "Image Generation/Style Filters" },

  { name: "AI Image To Video", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Text to Video Generator", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Image to Prompts", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Background Remover", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Image Beautifier", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Free Image Recognition", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Online Drawing Board", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Image Upscaler", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Qwen Image Editor", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Image Editor", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Image Watermark & Beautifier", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Watermark Remover", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Online PS", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Photo To Oil Painting", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Image OCR Converter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Compress Image Without Losing Quality", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Photo To Sketch", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Turn Photo Into Line Drawing", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Photo To Painting", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Photo Restoration", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Unblur Image", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Remove People From Photos", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Edit Text In Image", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Remove Text From Image", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI 2D To 3D Image Converter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Change Skin Color", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Age Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Clone Stamp Tool", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Object Remover", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Kolors Virtual Try On", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Barbie Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Minecraft Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Medieval Art", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Fisheye Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Add Beard To Photo", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "South Park Character Creator", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Vintage Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Outfit Generator", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Image Extender", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Young Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Hair Color Changer", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Smile Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Bald Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Skinny Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Remove Filter From Photo", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Sketch To Photo", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Old Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Image Combiner", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Motion Blur", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Add Shadow To Image", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Add White Background To Photo", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Silhouette Maker", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Change Background Color Of Photo", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Pokemon Trainer Generator", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Cut Out Image", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Blur Image", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Unpixelate Image", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Black And White Photo To Color", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Virtual Staging AI", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Emoji Remover", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Coloring Page Generator", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Nose Piercing Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Low Poly", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Short Hair Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Braces Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Remove Tattoo", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Pet Portrait Generator", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Photo Color Correction", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Wrinkle Remover", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Tattoo Generator", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Headshot Generator", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Vignette Effect", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Face Cut Out", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Powerpuff Girls", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Teeth Whitening", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Buzz Cut Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI No Beard Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI Eyebrow Filter", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Wan Image To Video", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "Paddleocr", category: "AI & Image Editing", subcategory: "Image Modification & Enhancement" },
  { name: "AI TTS Free", category: "AI & Image Editing", subcategory: "Video & Audio" },
  { name: "Text to Speech", category: "AI & Image Editing", subcategory: "Video & Audio" },
  { name: "Video Parser", category: "AI & Image Editing", subcategory: "Video & Audio" },
  { name: "AI YouTube Thumbnail Maker", category: "AI & Image Editing", subcategory: "Video & Audio" },

  // ========== DEVELOPMENT & CODE =========
  { name: "Online Code Compiler (C#,VB.NET,PHP,Java,more)", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "Python3 Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "Java Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "PHP Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "C Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "C++ Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "JS Code Runner", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "Golang Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "Rust Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "Lua Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "C# Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners", isRealDemo: true },
  { name: "Haskell Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  { name: "Lisp Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  { name: "Swift Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  { name: "Ruby Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  { name: "Kotlin Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  { name: "Erlang Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  { name: "Scala Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  { name: "Elixir Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  { name: "Perl Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  { name: "Clojure Online Compiler", category: "Development & Code", subcategory: "Compilers/Runners" },
  
  { name: "JSON Tool (JSON Editor)", category: "Development & Code", subcategory: "Editors/Formatters", isRealDemo: true },
  { name: "SQL Designer", category: "Development & Code", subcategory: "Editors/Formatters" },
  { name: "SQL Formatter", category: "Development & Code", subcategory: "Editors/Formatters" },
  { name: "CSS Tools", category: "Development & Code", subcategory: "Editors/Formatters" },
  { name: "HTML Editor", category: "Development & Code", subcategory: "Editors/Formatters" },
  { name: "XML Editor", category: "Development & Code", subcategory: "Editors/Formatters" },
  { name: "JavaScript Tools", category: "Development & Code", subcategory: "Editors/Formatters" },
  { name: "YAML Formatter", category: "Development & Code", subcategory: "Editors/Formatters" },
  { name: "Markdown HTML Converter", category: "Development & Code", subcategory: "Editors/Formatters", isRealDemo: true },

  { name: "JS Obfuscation", category: "Development & Code", subcategory: "Security/Obfuscation" },
  { name: "PHP Encrypt Decrypt", category: "Development & Code", subcategory: "Security/Obfuscation" },
  { name: "Python Obfuscator & Encryption Tool", category: "Development & Code", subcategory: "Security/Obfuscation" },
  { name: "Text Encryptor", category: "Development & Code", subcategory: "Security/Obfuscation" },
  { name: "PHP Base64 Encrypt & Decrypt Tool", category: "Development & Code", subcategory: "Security/Obfuscation" },
  { name: "Java Code Obfuscation Tool", category: "Development & Code", subcategory: "Security/Obfuscation" },

  { name: "Regex Tester", category: "Development & Code", subcategory: "Utilities", isRealDemo: true },
  { name: "Morse Translator", category: "Development & Code", subcategory: "Utilities", isRealDemo: true },
  { name: "Crontab Evaluator", category: "Development & Code", subcategory: "Utilities", isRealDemo: true },
  { name: "Password Generator", category: "Development & Code", subcategory: "Utilities", isRealDemo: true },
  { name: "APK Decompiler", category: "Development & Code", subcategory: "Utilities" },
  { name: "HTTP Simulator", category: "Development & Code", subcategory: "Utilities" },
  { name: "htaccess2Nginx", category: "Development & Code", subcategory: "Utilities" },
  { name: "Text Diff Tool", category: "Development & Code", subcategory: "Utilities" },
  { name: "WebSocket Test Tool", category: "Development & Code", subcategory: "Utilities" },
  { name: "cURL to Code Converter", category: "Development & Code", subcategory: "Utilities" },
  { name: "cdnjs CDN Tool", category: "Development & Code", subcategory: "Utilities" },

  { name: "DNS Checker Online", category: "Development & Code", subcategory: "Web/Network" },
  { name: "Domain Security Checker Tool", category: "Development & Code", subcategory: "Web/Network" },
  { name: "Website Port Checker", category: "Development & Code", subcategory: "Web/Network" },
  { name: "IP Address Lookup", category: "Development & Code", subcategory: "Web/Network" },

  // ========== CONVERSION & PDF =========
  { name: "PDF to Word Converter", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "PDF Password Remover", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "PDF to Image", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "PDF to Excel Converter", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "Word to PDF Converter", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "PDF to PPT Converter", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "PDF to TXT Converter", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "PDF to Base64", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "TXT to PDF Converter", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "Password Protect PDF Tool", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "Excel to PDF Converter", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "PDF to HTML Converter", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },
  { name: "PPT to PDF Converter", category: "Conversion & PDF", subcategory: "PDF Conversion/Editing" },

  { name: "Base64 to PDF", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Base64 Audio Converter", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Audio to Base64", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Base64 to Video", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "MP4 To Base64 Encoder", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Base64 to Image", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Base64 File Converter", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Base64 to Hex", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Base64 URL Converter", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Image to Base64", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Base64 to Text", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Hex to Base64", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "File to Base64", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Base64 URL Encoder", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Text to Base64", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },
  { name: "Base64 to ASCII", category: "Conversion & PDF", subcategory: "Base64 Encoding/Decoding", isRealDemo: true },

  { name: "Convert Tool", category: "Conversion & PDF", subcategory: "General Converters", isRealDemo: true },
  { name: "Byte Converter", category: "Conversion & PDF", subcategory: "General Converters", isRealDemo: true },
  { name: "Base Converter", category: "Conversion & PDF", subcategory: "General Converters", isRealDemo: true },
  { name: "CSV Converter", category: "Conversion & PDF", subcategory: "General Converters", isRealDemo: true },
  { name: "SVG2Image", category: "Conversion & PDF", subcategory: "General Converters" },

  // ========== SPECIALIZED CHINESE =========
  { name: "Chinese Calendar", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities", isRealDemo: true },
  { name: "Chinese Phone Number Lookup", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities" },
  { name: "Chinese Bazi Calculator", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities", isRealDemo: true },
  { name: "Chinese ID Lookup", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities" },
  { name: "Chinese Text Converter", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities" },
  { name: "Chinese Bank Card Lookup", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities" },
  { name: "Chinese Character Generator", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities" },
  { name: "Chinese Baby Name Generator", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities", isRealDemo: true },
  { name: "Chinese Salary & Tax Calculator", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities" },
  { name: "Chinese Oil Price Checker", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities" },
  { name: "Taoist Calendar", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities" },
  { name: "Buddhist Calendar", category: "Specialized Chinese", subcategory: "Chinese Heritage & Utilities" },

  // ========== GENERAL UTILITY =========
  { name: "URL Shortener", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "Mind Mapper", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "Barcode Generator", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "Jigsaw Puzzle Tool", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "FooPlot Complex Function Plotter", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "Scientific Notation Calculator", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "Unix Time Converter", category: "General Utility", subcategory: "General & Fun Utilities", isRealDemo: true },
  { name: "UML Timing Tool", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "Website Mirror Tool", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "SpongeBob Meme Generator", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "AI Profile Picture Generator", category: "General Utility", subcategory: "General & Fun Utilities" },
  { name: "AI Yearbook Photo", category: "General Utility", subcategory: "General & Fun Utilities", isRealDemo: true },
  { name: "AI LinkedIn Photo Generator", category: "General Utility", subcategory: "General & Fun Utilities" },
  // ========== NEW AI MODELS AND AGENTS =========
  { name: "Gemma", category: "AI & Image Editing", subcategory: "Text Models", isRealDemo: true },
  { name: "GPT 1", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "GPT 2", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "GPT 3", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "GPT J", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "GPT 4.40 Text", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "GPT 4.5", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "GPT 4.1", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "GPT OSS", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "GPT 5", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "Llama", category: "AI & Image Editing", subcategory: "Text Models", isRealDemo: true },
  { name: "01", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "03", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "04-mini", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "Qwen Base44", category: "AI & Image Editing", subcategory: "Text Models", isRealDemo: true },
  { name: "Claude Code", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "Cursor", category: "AI & Image Editing", subcategory: "Text Models" },
  { name: "Devstral", category: "AI & Image Editing", subcategory: "Text Models", isRealDemo: true },

  { name: "GitHub Copilot", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "Kimi", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "Qwen3-Coder", category: "Development & Code", subcategory: "Coding & Agents", isRealDemo: true },
  { name: "Replit", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "Xcode", category: "Development & Code", subcategory: "Coding & Agents" },

  { name: "Aurora", category: "AI & Image Editing", subcategory: "Image Models" },
  { name: "Firefly", category: "AI & Image Editing", subcategory: "Image Models" },
  { name: "Flux", category: "AI & Image Editing", subcategory: "Image Models", isRealDemo: true },
  { name: "GPT Image 1", category: "AI & Image Editing", subcategory: "Image Models" },
  { name: "Ideogram", category: "AI & Image Editing", subcategory: "Image Models" },
  { name: "Imagen", category: "AI & Image Editing", subcategory: "Image Models" },
  { name: "Midjourney", category: "AI & Image Editing", subcategory: "Image Models" },
  { name: "Qwen-Image", category: "AI & Image Editing", subcategory: "Image Models", isRealDemo: true },
  { name: "Recraft", category: "AI & Image Editing", subcategory: "Image Models" },
  { name: "Seedream", category: "AI & Image Editing", subcategory: "Image Models", isRealDemo: true },
  { name: "Stable Diffusion", category: "AI & Image Editing", subcategory: "Image Models", isRealDemo: true },

  { name: "Dream Machine", category: "AI & Image Editing", subcategory: "Video Models" },
  { name: "Hailuo AI", category: "AI & Image Editing", subcategory: "Video Models" },
  { name: "Kling", category: "AI & Image Editing", subcategory: "Video Models", isRealDemo: true },
  { name: "Midjourney Video", category: "AI & Image Editing", subcategory: "Video Models" },
  { name: "Runway Gen", category: "AI & Image Editing", subcategory: "Video Models" },
  { name: "Seedance", category: "AI & Image Editing", subcategory: "Video Models" },
  { name: "Sora", category: "AI & Image Editing", subcategory: "Video Models" },
  { name: "Veo", category: "AI & Image Editing", subcategory: "Video Models" },
  { name: "Wan", category: "AI & Image Editing", subcategory: "Video Models", isRealDemo: true },

  { name: "15.ai", category: "AI & Image Editing", subcategory: "Speech & Audio Models" },
  { name: "Eleven", category: "AI & Image Editing", subcategory: "Speech & Audio Models" },
  { name: "MiniMax Speech 2.5", category: "AI & Image Editing", subcategory: "Speech & Audio Models", isRealDemo: true },
  { name: "WaveNet", category: "AI & Image Editing", subcategory: "Speech & Audio Models" },
  { name: "Eleven Music", category: "AI & Image Editing", subcategory: "Speech & Audio Models" },
  { name: "Endel", category: "AI & Image Editing", subcategory: "Speech & Audio Models" },
  { name: "Lyria", category: "AI & Image Editing", subcategory: "Speech & Audio Models" },
  { name: "Riffusion", category: "AI & Image Editing", subcategory: "Speech & Audio Models" },
  { name: "Suno AI", category: "AI & Image Editing", subcategory: "Speech & Audio Models" },
  { name: "Udio", category: "AI & Image Editing", subcategory: "Speech & Audio Models" },

  { name: "Agentforce", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "AutoGLM", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "AutoGPT", category: "Development & Code", subcategory: "Coding & Agents", isRealDemo: true },
  { name: "ChatGPT Agent", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "Devin AI", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "Manus", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "OpenAI Codex", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "Operator", category: "Development & Code", subcategory: "Coding & Agents" },
  { name: "Replit Agent", category: "Development & Code", subcategory: "Coding & Agents" },
  
  { name: "01.AI", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "Aleph Alpha", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "Anthropic", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "Baichuan", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "Canva", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "Cognition AI", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "Cohere", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "Contextual AI", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "DeepSeek", category: "AI & Image Editing", subcategory: "Organizations & Frameworks", isRealDemo: true },
  { name: "ElevenLabs", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "Google DeepMind", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "HeyGen", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" },
  { name: "Hugging Face", category: "AI & Image Editing", subcategory: "Organizations & Frameworks" }
];
